sudo: required

language: elm
node_js: '10' # latest 10.x

elm-test: 0.19.0-rev4
elm-format: 0.8.1

cache:
  yarn: true
  directories:
    - node_modules


script:
  #  - cd tests
  - elm-format --validate . && elm-test
  - elm make ./src/Main.elm --optimize --output=./gh-pages/bundle.js
#  - node ./ci.js

after_success:
  - git clone -b assets --single-branch https://github.com/$TRAVIS_REPO_SLUG.git ./gh-pages/assets

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: gh-pages
  on:
    branch: revision3
