sudo: required

language: node

cache:
  directories:
    - tests/elm-stuff
    - tests/node_modules
    - tests/stats.json
    - $HOME/.aerokube
    - $HOME/.cm

matrix:
    include:
        ### CHROME DRIVER ###
        - os: linux
          env: |
            ELM_VERSION=latest
            TARGET_NODE_VERSION=node
            DRIVER_NAME="Chrome Linux"
            ELM_HOME=$HOME/.elm-linux
          services:
            - docker

        - os: osx
          env: |
            ELM_VERSION=latest
            TARGET_NODE_VERSION=node
            DRIVER_NAME="Chrome OSX"
            ELM_HOME=$HOME/.elm-osx
          addons:
            chrome: stable



before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION

install:
  - yarn --cwd tests
  - yarn global add elm@$ELM_VERSION
  - node --version
  - npm --version
  - yarn --version
  - elm --version
  - export PATH=$PATH:$PWD
  # - if ! [ -f ./cm ]; then curl -s https://aerokube.com/cm/bash | bash; fi
  - curl -s https://aerokube.com/cm/bash | bash;
  - ./cm selenoid start --vnc --tmpfs 128


script:
  # - elm-format --validate src/
  - cd tests
  - elm make ./src/Main.elm --optimize --output=bundle.js
  - node ./ci.js
